apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: <%= projectName %>
    role: api
  name: <%= projectName %>
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <%= projectName %>
  template:
    metadata:
      labels:
        app: <%= projectName %>
    spec:
      containers:
      - name: <%= projectName %>
        image: <%= ecrRepository %>:<%= projectName %>-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4003
          name: node-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 4003
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <%= projectName %>
  name: <%= projectName %>
  namespace: applications
spec:
  ports:
  - name: http
    port: 4003
  selector:
    app: <%= projectName %>
